import { chmod, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

export interface BrowserCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires: number;
  httpOnly?: boolean;
  secure?: boolean;
}

export interface BrowserPage {
  goto: (url: string, options?: { waitUntil?: string }) => Promise<unknown>;
  waitForTimeout: (ms: number) => Promise<void>;
}

export interface BrowserContext {
  newPage: () => Promise<BrowserPage>;
  cookies: () => Promise<BrowserCookie[]>;
  storageState?: (options: { path: string }) => Promise<unknown>;
  close?: () => Promise<void>;
}

export interface BrowserInstance {
  newContext: () => Promise<BrowserContext>;
  close: () => Promise<void>;
}

export interface BrowserLaunchOptions {
  headless: boolean;
  channel?: string;
}

export type ChromiumLauncher = (options: BrowserLaunchOptions) => Promise<BrowserInstance>;

export interface DouyinAuthInput {
  outPath?: string;
  storagePath?: string;
  url?: string;
  timeoutSec?: number;
  pollIntervalMs?: number;
  headless?: boolean;
}

export interface DouyinAuthResult {
  cookiesPath: string;
  storagePath?: string;
  cookieCount: number;
  detectedCookies: string[];
}

export interface DouyinAuthDeps {
  launchChromium?: ChromiumLauncher;
}

const DEFAULT_AUTH_URL = 'https://www.douyin.com/';
const DEFAULT_COOKIES_PATH = path.join('.openvideo', 'cookies', 'douyin-cookies.txt');
const REQUIRED_DOUYIN_COOKIES = ['ttwid', 'odin_tt', 'passport_csrf_token'];

export async function authenticateDouyin(
  input: DouyinAuthInput = {},
  deps: DouyinAuthDeps = {},
): Promise<DouyinAuthResult> {
  const launchChromium = deps.launchChromium ?? (await loadPlaywrightChromium());
  const cookiesPath = path.resolve(input.outPath ?? DEFAULT_COOKIES_PATH);
  const storagePath = input.storagePath ? path.resolve(input.storagePath) : undefined;
  const timeoutMs = Math.max(0.001, input.timeoutSec ?? 300) * 1000;
  const pollIntervalMs = Math.max(250, input.pollIntervalMs ?? 1000);
  const browser = await launchChromium({ headless: input.headless ?? false });
  let context: BrowserContext | undefined;

  try {
    context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(input.url ?? DEFAULT_AUTH_URL, { waitUntil: 'domcontentloaded' });
    const cookies = await waitForRequiredCookies(context, page, timeoutMs, pollIntervalMs);
    await writeNetscapeCookieFile(cookiesPath, cookies);
    if (storagePath && context.storageState) {
      await mkdir(path.dirname(storagePath), { recursive: true });
      await context.storageState({ path: storagePath });
      await chmod(storagePath, 0o600).catch(() => undefined);
    }
    return {
      cookiesPath,
      ...(storagePath ? { storagePath } : {}),
      cookieCount: cookies.length,
      detectedCookies: REQUIRED_DOUYIN_COOKIES.filter((name) => cookies.some((cookie) => cookie.name === name)),
    };
  } finally {
    await context?.close?.().catch(() => undefined);
    await browser.close().catch(() => undefined);
  }
}

async function waitForRequiredCookies(
  context: BrowserContext,
  page: BrowserPage,
  timeoutMs: number,
  pollIntervalMs: number,
): Promise<BrowserCookie[]> {
  const deadline = Date.now() + timeoutMs;
  let lastCookies: BrowserCookie[] = [];

  while (Date.now() <= deadline) {
    lastCookies = await context.cookies();
    if (missingRequiredCookies(lastCookies).length === 0) {
      return lastCookies;
    }
    await page.waitForTimeout(Math.min(pollIntervalMs, Math.max(0, deadline - Date.now())));
  }

  const missing = missingRequiredCookies(lastCookies);
  throw new Error(
    `Timed out waiting for Douyin login cookies. Missing: ${missing.join(', ')}. Scan the QR code and keep the browser open until login completes.`,
  );
}

function missingRequiredCookies(cookies: BrowserCookie[]): string[] {
  return REQUIRED_DOUYIN_COOKIES.filter((name) => !cookies.some((cookie) => cookie.name === name && cookie.value));
}

export async function writeNetscapeCookieFile(filePath: string, cookies: BrowserCookie[]): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by OpenVideo. Treat this file like a password.',
    ...cookies.map(formatNetscapeCookie),
    '',
  ];
  await writeFile(filePath, lines.join('\n'), 'utf8');
  await chmod(filePath, 0o600).catch(() => undefined);
}

function formatNetscapeCookie(cookie: BrowserCookie): string {
  const domain = cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain;
  const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
  const pathValue = cookie.path || '/';
  const secure = cookie.secure ? 'TRUE' : 'FALSE';
  const expires = cookie.expires > 0 ? String(Math.floor(cookie.expires)) : '0';
  return [domain, includeSubdomains, pathValue, secure, expires, cookie.name, cookie.value].join('\t');
}

interface PlaywrightModule {
  chromium: {
    launch: (options: BrowserLaunchOptions) => Promise<BrowserInstance>;
  };
}

async function loadPlaywrightChromium(): Promise<ChromiumLauncher> {
  try {
    const dynamicImport = new Function('specifier', 'return import(specifier)') as (
      specifier: string,
    ) => Promise<unknown>;
    const playwright = (await dynamicImport('playwright')) as PlaywrightModule;
    return (options) => playwright.chromium.launch(withDefaultChromeChannel(options));
  } catch (error) {
    throw new Error(
      [
        'Playwright is required for `openvideo auth douyin`.',
        'Install it with:',
        '  npm install --save-dev playwright',
        '  npx playwright install chromium',
        error instanceof Error ? `Original error: ${error.message}` : String(error),
      ].join('\n'),
    );
  }
}

function withDefaultChromeChannel(options: BrowserLaunchOptions): BrowserLaunchOptions {
  if (process.env.OPENVIDEO_PLAYWRIGHT_CHANNEL === 'bundled') {
    return options;
  }
  return {
    ...options,
    channel: process.env.OPENVIDEO_PLAYWRIGHT_CHANNEL || 'chrome',
  };
}
